name: Update TryHackMe Badge

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

permissions:
  contents: write

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create assets folder
        run: mkdir -p assets

      - name: Download TryHackMe Badge
        run: |
          curl -L -o assets/thm_propic.png "https://tryhackme.com/badge/${{ secrets.THM_USERNAME }}"

      - name: Commit and Push
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add assets/thm_propic.png
          git diff --cached --quiet || git commit -m "Updated TryHackMe Badge"
          git push
